### ISSUE TITLE
浏览器插件: tifoo (免费, 开源的tailwindcss开发助手)

### ISSUE THREAD

**Issue by actopas** [hr98w/solopreneur#8]

**Comment by bingoogolapple** [comment]
@actopas  请教个问题，add classes 下拉选框里的数据源是如何拿到全集的？

目前在低代码里也加了个tailwindcss 选择的功能，但是是通过 gpt 生成的类名全集（大概率不全）

**Comment by actopas** [comment]
@bingoogolapple https://github.com/actopas/tailwind-classes-generator 这里，但是数据量非常大，大概超过了14万个原子类
